// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {converters} from '../models';

export function AddColumn(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:boolean,arg7:string):Promise<void>;

export function AlterColumnType(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<void>;

export function ConnectToDatabase(arg1:string):Promise<void>;

export function CreateCollection(arg1:string,arg2:string):Promise<void>;

export function CreateConnection(arg1:converters.PublicConnection):Promise<converters.PublicConnection>;

export function DeleteConnection(arg1:string):Promise<void>;

export function DeleteDocument(arg1:string,arg2:string,arg3:string):Promise<void>;

export function DeleteKVEntry(arg1:string,arg2:string):Promise<void>;

export function DisconnectFromDatabase(arg1:string):Promise<void>;

export function DropCollection(arg1:string,arg2:string):Promise<void>;

export function DropColumn(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function DropTable(arg1:string,arg2:string,arg3:string):Promise<void>;

export function ExecuteQuery(arg1:string,arg2:string):Promise<converters.PublicQueryResult>;

export function ExplainQuery(arg1:string,arg2:string,arg3:boolean):Promise<converters.PublicExplainResult>;

export function GetCollections(arg1:string):Promise<Array<converters.PublicNoSQLCollection>>;

export function GetConnection(arg1:string):Promise<converters.PublicConnection>;

export function GetDocuments(arg1:string,arg2:string,arg3:string,arg4:number):Promise<Array<Record<string, any>>>;

export function GetEnums(arg1:string):Promise<Array<converters.PublicSQLEnum>>;

export function GetFunctions(arg1:string):Promise<Array<converters.PublicSQLFunction>>;

export function GetKVEntry(arg1:string,arg2:string):Promise<converters.PublicKVEntry>;

export function GetKVStats(arg1:string):Promise<converters.PublicKVStats>;

export function GetKeys(arg1:string,arg2:string,arg3:number):Promise<Array<converters.PublicKVEntry>>;

export function GetQueryHistory(arg1:string):Promise<Array<converters.PublicHistoryEntry>>;

export function GetSequences(arg1:string):Promise<Array<converters.PublicSQLSequence>>;

export function GetSidebarTree():Promise<string>;

export function GetTableData(arg1:string,arg2:string,arg3:string,arg4:number,arg5:number):Promise<converters.PublicQueryResult>;

export function GetTables(arg1:string):Promise<Array<converters.PublicSQLTable>>;

export function GetTriggers(arg1:string):Promise<Array<converters.PublicSQLTrigger>>;

export function GetViews(arg1:string):Promise<Array<converters.PublicSQLView>>;

export function InsertDocument(arg1:string,arg2:string,arg3:Record<string, any>):Promise<Record<string, any>>;

export function ListConnections():Promise<Array<converters.PublicConnection>>;

export function RefreshMaterializedView(arg1:string,arg2:string,arg3:string):Promise<void>;

export function RenameColumn(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<void>;

export function SaveSidebarTree(arg1:string):Promise<void>;

export function SetColumnDefault(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<void>;

export function SetColumnNullable(arg1:string,arg2:string,arg3:string,arg4:string,arg5:boolean):Promise<void>;

export function SetKVEntry(arg1:string,arg2:string,arg3:string,arg4:any):Promise<void>;

export function TestConnection(arg1:converters.PublicConnection):Promise<void>;

export function UpdateConnection(arg1:converters.PublicConnection):Promise<converters.PublicConnection>;

export function UpdateDocument(arg1:string,arg2:string,arg3:string,arg4:Record<string, any>):Promise<Record<string, any>>;
