// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddColumn(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['main']['App']['AddColumn'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function AlterColumnType(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['AlterColumnType'](arg1, arg2, arg3, arg4, arg5);
}

export function ConnectToDatabase(arg1) {
  return window['go']['main']['App']['ConnectToDatabase'](arg1);
}

export function CreateCollection(arg1, arg2) {
  return window['go']['main']['App']['CreateCollection'](arg1, arg2);
}

export function CreateConnection(arg1) {
  return window['go']['main']['App']['CreateConnection'](arg1);
}

export function DeleteConnection(arg1) {
  return window['go']['main']['App']['DeleteConnection'](arg1);
}

export function DeleteDocument(arg1, arg2, arg3) {
  return window['go']['main']['App']['DeleteDocument'](arg1, arg2, arg3);
}

export function DeleteKVEntry(arg1, arg2) {
  return window['go']['main']['App']['DeleteKVEntry'](arg1, arg2);
}

export function DisconnectFromDatabase(arg1) {
  return window['go']['main']['App']['DisconnectFromDatabase'](arg1);
}

export function DropCollection(arg1, arg2) {
  return window['go']['main']['App']['DropCollection'](arg1, arg2);
}

export function DropColumn(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['DropColumn'](arg1, arg2, arg3, arg4);
}

export function DropTable(arg1, arg2, arg3) {
  return window['go']['main']['App']['DropTable'](arg1, arg2, arg3);
}

export function ExecuteQuery(arg1, arg2) {
  return window['go']['main']['App']['ExecuteQuery'](arg1, arg2);
}

export function ExplainQuery(arg1, arg2, arg3) {
  return window['go']['main']['App']['ExplainQuery'](arg1, arg2, arg3);
}

export function GetCollections(arg1) {
  return window['go']['main']['App']['GetCollections'](arg1);
}

export function GetConnection(arg1) {
  return window['go']['main']['App']['GetConnection'](arg1);
}

export function GetDocuments(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GetDocuments'](arg1, arg2, arg3, arg4);
}

export function GetEnums(arg1) {
  return window['go']['main']['App']['GetEnums'](arg1);
}

export function GetFunctions(arg1) {
  return window['go']['main']['App']['GetFunctions'](arg1);
}

export function GetKVEntry(arg1, arg2) {
  return window['go']['main']['App']['GetKVEntry'](arg1, arg2);
}

export function GetKVStats(arg1) {
  return window['go']['main']['App']['GetKVStats'](arg1);
}

export function GetKeys(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetKeys'](arg1, arg2, arg3);
}

export function GetQueryHistory(arg1) {
  return window['go']['main']['App']['GetQueryHistory'](arg1);
}

export function GetSequences(arg1) {
  return window['go']['main']['App']['GetSequences'](arg1);
}

export function GetSidebarTree() {
  return window['go']['main']['App']['GetSidebarTree']();
}

export function GetTableData(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['GetTableData'](arg1, arg2, arg3, arg4, arg5);
}

export function GetTables(arg1) {
  return window['go']['main']['App']['GetTables'](arg1);
}

export function GetTriggers(arg1) {
  return window['go']['main']['App']['GetTriggers'](arg1);
}

export function GetViews(arg1) {
  return window['go']['main']['App']['GetViews'](arg1);
}

export function InsertDocument(arg1, arg2, arg3) {
  return window['go']['main']['App']['InsertDocument'](arg1, arg2, arg3);
}

export function ListConnections() {
  return window['go']['main']['App']['ListConnections']();
}

export function RefreshMaterializedView(arg1, arg2, arg3) {
  return window['go']['main']['App']['RefreshMaterializedView'](arg1, arg2, arg3);
}

export function RenameColumn(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['RenameColumn'](arg1, arg2, arg3, arg4, arg5);
}

export function SaveSidebarTree(arg1) {
  return window['go']['main']['App']['SaveSidebarTree'](arg1);
}

export function SetColumnDefault(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['SetColumnDefault'](arg1, arg2, arg3, arg4, arg5);
}

export function SetColumnNullable(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['SetColumnNullable'](arg1, arg2, arg3, arg4, arg5);
}

export function SetKVEntry(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SetKVEntry'](arg1, arg2, arg3, arg4);
}

export function TestConnection(arg1) {
  return window['go']['main']['App']['TestConnection'](arg1);
}

export function UpdateConnection(arg1) {
  return window['go']['main']['App']['UpdateConnection'](arg1);
}

export function UpdateDocument(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['UpdateDocument'](arg1, arg2, arg3, arg4);
}
